let { MONGO_IP, MONGO_PORT, MONGO_USER, MONGO_PASSWORD, REDIS_URL, REDIS_PORT, SESSION_SECRET } = process.env

MONGO_IP ||= 'mongo'
MONGO_PORT ||= 27017

REDIS_URL ||= 'redis'
REDIS_PORT ||= 6379

module.exports = { MONGO_IP, MONGO_PORT, MONGO_USER, MONGO_PASSWORD, REDIS_URL, REDIS_PORT, SESSION_SECRET }
